### PR TITLE
Adding kate syntax highlighting xml file

### PR DESCRIPTION
**Pull request by aleskandro**
Here the pull request for the  syntax highlighting xml of kate for eduMips64. As soon as possibile the vim one.
Bye

### CODE REVIEW

**Comment by lupino3** [comment]
I doubt your pull request broke the continuous integration testing.. I'll fix it before merging this pull request.

**Comment by aleskandro** [comment]
I read the log and it seems the an option for pip is no more available (--use-mirrors)

**Comment by lupino3** [comment]
Correct :) I fixed it in commit a6e2ca.

**Comment by lupino3** [comment]
I'll merge your pull request. Thanks!

**Comment by aleskandro** [comment]
All right! Have a nice evening

**Pull request merged**
